export declare enum SIMPLENETWORK {
    DELETE = "SIMPLENETWORK_DELETE",
    FAILURE = "SIMPLENETWORK_FAILURE",
    GET = "SIMPLENETWORK_GET",
    HEAD = "SIMPLENETWORK_HEAD",
    PATCH = "SIMPLENETWORK_PATCH",
    POST = "SIMPLENETWORK_POST",
    PUT = "SIMPLENETWORK_PUT",
    SUCCESS = "SIMPLENETWORK_SUCCESS"
}
export declare enum SIMPLEFORM {
    INPUT = "SIMPLEFORM_INPUT",
    FAILURE = "SIMPLEFORM_FAILURE",
    NUMBER = "SIMPLEFORM_NUMBER",
    SUCCESS = "SIMPLEFORM_SUCCESS",
    TOGGLE = "SIMPLEFORM_TOGGLE"
}
