window.Blueprint = {}
window.Blueprint.Core = require("@blueprintjs/core")
window.Blueprint.Datetime = require("@blueprintjs/datetime")
window.Blueprint.Icons = require("@blueprintjs/icons")
window.Blueprint.Select = require("@blueprintjs/select")
window.Axios = require("axios")
window.ConnectedReactRouter = require("connected-react-router")
window.HistoryNPM = require("history")
window.React = require("react")
window.ReactDom = require("react-dom")
window.ReactHelmet = require("react-helmet")
window.ReactRedux = require("react-redux")
window.ReactRouter = require("react-router")
window.ReactRouterDom = require("react-router-dom")
window.Redux = require("redux")
window.ReduxSaga = require("redux-saga")
window.ReduxSagaEffects = require("redux-saga/effects")
window.Reselect = require("reselect")
window.ReReselect = require("re-reselect")

//  Will be removed in next major release to thin out Vendors
window.Dayjs = require("dayjs")
window.Immutable = require("immutable")
window.ReactHotLoader = require("react-hot-loader")
window.StyledComponents = require("styled-components")
