import * as fs from "fs-extra"
import { Files, IMiskTabJSON, JsonOptions } from "."
import {
  createPackage,
  createTsconfig,
  generatedByCLI,
  gitignore,
  tslint,
  webpack
} from "./templates"
import { getVersion } from "./changelog"

export const generateBuildFiles = async (...args: any) => {
  const dir = args[0]
  let pkg = {}
  try {
    pkg = await fs.readJson(`${dir}/${Files.package}`)
  } catch (e) {}
  const miskTab: IMiskTabJSON = await fs.readJson(`${dir}/${Files.miskTab}`)
  // Write out fresh files
  await [
    fs.writeJson(
      `${dir}/${Files.tsconfig}`,
      createTsconfig(miskTab),
      JsonOptions
    ),
    fs.writeJson(`${dir}/${Files.tslint}`, tslint, JsonOptions),
    fs.writeJson(
      `${dir}/${Files.package}`,
      createPackage(miskTab, pkg),
      JsonOptions
    ),
    fs.writeFile(`${dir}/${Files.gitignore}`, gitignore),
    fs.writeFile(`${dir}/${Files.webpack}`, webpack)
  ]

  // Append non-package JSON files with generated by comment
  await fs.writeFile(`${dir}/${Files.tsconfig}`, generatedByCLI, { flag: "a" })
  await fs.writeFile(`${dir}/${Files.tslint}`, generatedByCLI, { flag: "a" })
  console.log(
    `[GENERATE] Up to date build files generated using Misk Web version ${getVersion(
      miskTab.version
    )}`
  )
}
